### ISSUE TITLE
`AttributeError: update_local_metadata` after calling `set_metadata`

### ISSUE THREAD

**Issue by egoldschmidt** [livekit/python-sdks#224]
When trying to update the metadata for a local participant, I'm seeing this error:

```
Traceback (most recent call last):
  File "...", line 245, in ...
    await self._agent.set_metadata(
  File "/Users/evan/Projects/portola/livekit-worker/.venv/lib/python3.12/site-packages/livekit/rtc/participant.py", line 170, in set_metadata
    await queue.wait_for(
  File "/Users/evan/Projects/portola/livekit-worker/.venv/lib/python3.12/site-packages/livekit/rtc/_utils.py", line 85, in wait_for
    if fnc(event):
       ^^^^^^^^^^
  File "/Users/evan/Projects/portola/livekit-worker/.venv/lib/python3.12/site-packages/livekit/rtc/participant.py", line 171, in <lambda>
    lambda e: e.update_local_metadata.async_id
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: update_local_metadata
```

I noticed that the function signature went from `update_local_metadata` to `set_metadata` in this latest release, so possible I'm running an outdate dependency somehow?

Deps:
  * livekit-agents 0.8.0
  * livekit-api 0.6.0
  * livekit-protocol 0.6.0
  * livekit 0.12.0.dev1

**Comment by theomonnom** [comment]
Hey, we are going to take a look at this today

**Comment by keepingitneil** [comment]
Saw another report of something similar. Looking at it now

**Comment by keepingitneil** [comment]
Fixed in https://github.com/livekit/python-sdks/pull/226. Release in `0.12.1`
