### ISSUE TITLE
rtc sdk: publish audio from local participant

### ISSUE THREAD

**Issue by Kedaqusa1604** [livekit/python-sdks#258]
Hi there, I'd like to know how can I publish audio (local wav file) to a room from a local_participant. This is what my code looks like:

```python

async def main(room: rtc.Room) -> None:
    @room.on("participant_disconnected")
    def on_participant_disconnect(participant: rtc.Participant, *_):
        logging.info("participant disconnected: %s", participant.identity)

    token = (
        api.AccessToken()
        .with_identity("python-publisher")
        .with_name("Python Publisher")
        .with_grants(
            api.VideoGrants(
                room_join=True,
                room="room-test",
            )
        )
        .to_jwt()
    )
    url = os.getenv("LIVEKIT_URL")

    logging.info("connecting to %s", url)

    try:
        await room.connect(
            url,
            token,
            options=rtc.RoomOptions(
                auto_subscribe=True,
            ),
        )
        logging.info("connected to room %s", room.name)
    except rtc.ConnectError as e:
        logging.error("failed to connect to the room: %s", e)
        return
   

    with wave.open(wav_filepath, 'rb') as wav_file:
        channels = wav_file.getnchannels()
        sample_rate = wav_file.getframerate()
        data_size = wav_file.getnframes()

        source = rtc.AudioSource(sample_rate, channels)
        track = rtc.LocalAudioTrack.create_audio_track("sinewave", source)
        options = rtc.TrackPublishOptions()
        options.source = rtc.TrackSource.SOURCE_MICROPHONE
        publication = await room.local_participant.publish_track(track, options)
        logging.info("published track %s", publication.sid)

        frame_duration = 1
        num_samples = sample_rate * frame_duration

        buffer = np.zeros(num_samples * channels, dtype=np.int16)

        for _ in range(0, data_size, num_samples):
            frames = wav_file.readframes(num_samples)
            if not frames:
                break
            
            num_frames = len(frames) // 2
            buffer[:num_frames] = np.frombuffer(frames, dtype=np.int16)

            frame = rtc.AudioFrame(
                buffer, 
                sample_rate, 
                channels, 
                len(frames) // 2 // channels
            )

            await source.capture_frame(frame)

```

But I'm getting the following error:

```python
  Traceback (most recent call last):
    File "/home/ec2-user/environment/LiveKit/cari/publish_wav.py", line 96, in main
      frame = rtc.AudioFrame(
    File "/home/ec2-user/environment/LiveKit/venv/lib/python3.10/site-packages/livekit/rtc/audio_frame.py", line 34, in __init__
      raise ValueError(
  ValueError: data length must be >= num_channels * samples_per_channel * sizeof(int16)
```

Thanks in advance for any help

**Comment by davidzhao** [comment]
did you try the example [here](https://github.com/livekit/python-sdks/blob/main/examples/publish_wave.py)?

**Comment by Kedaqusa1604** [comment]
Yes I did, and it worked as expected, but in each approach that I try to send the audio from a wav file, I get this error.
Fun fact: If I comment the lines that throws the error, it works.

**Comment by Kedaqusa1604** [comment]
I made it work, Here's the full example, just in case...

```python
    with wave.open(str(wav_filepath), 'rb') as wav_file:
        channels = wav_file.getnchannels()
        sample_rate = wav_file.getframerate()
        data_size = wav_file.getnframes()
        print(f'Channels: {channels}, Sample Rate: {sample_rate}, Frames: {data_size}')

        source = rtc.AudioSource(sample_rate, channels)
        track = rtc.LocalAudioTrack.create_audio_track("audio", source)
        options = rtc.TrackPublishOptions()
        options.source = rtc.TrackSource.SOURCE_MICROPHONE
        publication = await room.local_participant.publish_track(track, options)

        logging.info("published track %s", publication.sid)

        frame_duration = 1  # seconds
        num_samples = sample_rate * frame_duration

        for _ in range(0, data_size, num_samples):
            frames = wav_file.readframes(num_samples)

            if not frames:
                break
            
            num_frames = len(frames) // 2 # ChatGPT: The // 2 is used because the frames returned by wav_file.readframes() is a byte string, and each sample in the WAV file is typically represented by 2 bytes (16 bits). Since we are converting the byte data to 16-bit integers (np.int16), we divide the length of the byte data by 2 to get the actual number of samples (or "frames").

            buffer_aux = np.frombuffer(frames, dtype=np.int16)
            
            frame = rtc.AudioFrame.create(
                sample_rate = sample_rate,
                num_channels = channels,
                samples_per_channel = num_frames // channels
            )

            audio_data = np.frombuffer(frame.data, dtype=np.int16)
            np.copyto(audio_data, buffer_aux)

            await source.capture_frame(frame)
```

Thanks @davidzhao for your help 😃
