### ISSUE TITLE
[ASYNCIO EVENT_LOOP] - ROOM RTC keeps a background task even after disconnected 

### ISSUE THREAD

**Issue by AutoScrape123TX** [livekit/python-sdks#327]
When you use a custom loop in a Thread and you close this event loop. You will have this error at the end.
Quite similar to https://github.com/livekit/python-sdks/issues/218

```
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dev/apps/predictive_dialer_app/services/executor/dialer_executor_service.py", line 141, in _launch_agent_with_async_into_room
    new_event_loop.run_until_complete(self._agent_conversation_run(call_task=call_task))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1978, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/dev/apps/predictive_dialer_app/services/executor/dialer_executor_service.py", line 329, in _send_agent_conversation_into_room
    await conversation.start_room(conversation_id=call_task.conversation_id)
  File "/opt/dev/dev/streaming/livekit/livekit_conversation_manual.py", line 51, in start_room
    await self.room.connect(url=os.getenv("LIVEKIT_URL"), token=access_token, options=room_options)
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/room.py", line 397, in connect
    self._task = self._loop.create_task(self._listen_task())
task: <Task pending name='Task-21' coro=<Room._listen_task() running at /root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/room.py:422> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> created at /root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/room.py:397>
Exception ignored in: <coroutine object Room._listen_task at 0x7fb093fef5b0>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/room.py", line 422, in _listen_task
    event = await self._ffi_queue.get()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/queues.py", line 160, in get
    getter.cancel()  # Just in case getter is not done yet.
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

When using a custom event loop in a thread to create a room rtc connection, we see that even after `room.disconnect()` and safe `room.__del__()`, there's still a pending Task waiting for input in an infinite loop.

Add a timeout logic and `while self.is_connected()` to this please
`livekit/rtc/room.py`
```
    async def _listen_task(self) -> None:
        # listen to incoming room events
        while True:
            event = await self._ffi_queue.get()
            if event.room_event.room_handle == self._ffi_handle.handle:  # type: ignore
                if event.room_event.HasField("eos"):
                    break

                try:
                    self._on_room_event(event.room_event)
                except Exception:
                    logging.exception(
                        "error running user callback for %s: %s",
                        event.room_event.WhichOneof("message"),
                        event.room_event,
                    )

            # wait for the subscribers to process the event
            # before processing the next one
            self._room_queue.put_nowait(event)
            await self._room_queue.join()
```

**Comment by AutoScrape123TX** [comment]
Okay finally found the bug, I was closing the room manually before let track subscribers receive the track unsubscribe from every leaving participants. Ended removing all participants, and then let livekit send unsubscribe track event to every other room's remaining participants, avoiding the missing `event.room_event.HasField("eos")` causing infinite loop.
