### ISSUE TITLE
Cannot import livekit version 0.4.6

### ISSUE THREAD

**Issue by TheNha** [livekit/python-sdks#78]
Hi. 
I installed livekit version 0.4.6, but when I used face_landmark.py in examples, I got an error. 

(python-sdks) livekit@ubuntu:~/Projects/python-sdks$ python examples/face_landmark/face_landmark.py
Traceback (most recent call last):
File "examples/face_landmark/face_landmark.py", line 12, in <module>
from livekit import rtc
File "/home/livekit/Projects/python-sdks/lib/python3.8/site-packages/livekit/__init__.py", line 28, in <module>
from .audio_frame import AudioFrame
File "/home/livekit/Projects/python-sdks/lib/python3.8/site-packages/livekit/audio_frame.py", line 17, in <module>
from ._ffi_client import FfiHandle, ffi_client
File "/home/livekit/Projects/python-sdks/lib/python3.8/site-packages/livekit/_ffi_client.py", line 25, in <module>
from ._utils import Queue
File "/home/livekit/Projects/python-sdks/lib/python3.8/site-packages/livekit/_utils.py", line 27, in <module>
class Queue(asyncio.Queue[T]):
TypeError: 'type' object is not subscriptable

I'm using ubuntu version 20.04, and python version 3.8.10. Please help me.
Thank you.

**Comment by anhtu-phan** [comment]
Hello, could you please share how can you fix this error?

Thank you!
